create table "public"."match_scores" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "match" bigint,
    "score_team1" integer,
    "score_team2" integer
);


alter table "public"."match_scores" enable row level security;

create table "public"."matchs" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "team1" bigint not null,
    "team2" bigint not null,
    "month" smallint not null,
    "tournament" bigint not null default '1'::bigint
);


alter table "public"."matchs" enable row level security;

create table "public"."players" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null default '255'::character varying,
    "tel" character varying not null default '20'::character varying
);


alter table "public"."players" enable row level security;

create table "public"."teams" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null default '255'::character varying,
    "player1" bigint,
    "player2" bigint
);


alter table "public"."teams" enable row level security;

create table "public"."tournament_teams" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "team" bigint not null,
    "tournament" bigint
);


create table "public"."tournaments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "year" integer not null,
    "name" character varying default '255'::character varying
);


alter table "public"."tournaments" enable row level security;

CREATE UNIQUE INDEX match_scores_pkey ON public.match_scores USING btree (id);

CREATE UNIQUE INDEX matchs_pkey ON public.matchs USING btree (id);

CREATE UNIQUE INDEX players_pkey ON public.players USING btree (id);

CREATE UNIQUE INDEX teams_pkey ON public.teams USING btree (id);

CREATE UNIQUE INDEX tournament_pkey ON public.tournaments USING btree (id);

CREATE UNIQUE INDEX tournament_teams_pkey ON public.tournament_teams USING btree (id);

CREATE UNIQUE INDEX tournament_year_key ON public.tournaments USING btree (year);

alter table "public"."match_scores" add constraint "match_scores_pkey" PRIMARY KEY using index "match_scores_pkey";

alter table "public"."matchs" add constraint "matchs_pkey" PRIMARY KEY using index "matchs_pkey";

alter table "public"."players" add constraint "players_pkey" PRIMARY KEY using index "players_pkey";

alter table "public"."teams" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";

alter table "public"."tournament_teams" add constraint "tournament_teams_pkey" PRIMARY KEY using index "tournament_teams_pkey";

alter table "public"."tournaments" add constraint "tournament_pkey" PRIMARY KEY using index "tournament_pkey";

alter table "public"."match_scores" add constraint "match_scores_match_fkey" FOREIGN KEY (match) REFERENCES matchs(id) not valid;

alter table "public"."match_scores" validate constraint "match_scores_match_fkey";

alter table "public"."matchs" add constraint "matchs_month_check" CHECK ((month > 0)) not valid;

alter table "public"."matchs" validate constraint "matchs_month_check";

alter table "public"."matchs" add constraint "matchs_team1_fkey" FOREIGN KEY (team1) REFERENCES teams(id) not valid;

alter table "public"."matchs" validate constraint "matchs_team1_fkey";

alter table "public"."matchs" add constraint "matchs_team2_fkey" FOREIGN KEY (team2) REFERENCES teams(id) not valid;

alter table "public"."matchs" validate constraint "matchs_team2_fkey";

alter table "public"."matchs" add constraint "matchs_tournament_fkey" FOREIGN KEY (tournament) REFERENCES tournaments(id) not valid;

alter table "public"."matchs" validate constraint "matchs_tournament_fkey";

alter table "public"."teams" add constraint "teams_player1_fkey" FOREIGN KEY (player1) REFERENCES players(id) not valid;

alter table "public"."teams" validate constraint "teams_player1_fkey";

alter table "public"."teams" add constraint "teams_player2_fkey" FOREIGN KEY (player2) REFERENCES players(id) not valid;

alter table "public"."teams" validate constraint "teams_player2_fkey";

alter table "public"."tournament_teams" add constraint "tournament_teams_team_fkey" FOREIGN KEY (team) REFERENCES teams(id) not valid;

alter table "public"."tournament_teams" validate constraint "tournament_teams_team_fkey";

alter table "public"."tournament_teams" add constraint "tournament_teams_tournament_fkey" FOREIGN KEY (tournament) REFERENCES tournaments(id) not valid;

alter table "public"."tournament_teams" validate constraint "tournament_teams_tournament_fkey";

alter table "public"."tournaments" add constraint "tournament_year_key" UNIQUE using index "tournament_year_key";

grant delete on table "public"."match_scores" to "anon";

grant insert on table "public"."match_scores" to "anon";

grant references on table "public"."match_scores" to "anon";

grant select on table "public"."match_scores" to "anon";

grant trigger on table "public"."match_scores" to "anon";

grant truncate on table "public"."match_scores" to "anon";

grant update on table "public"."match_scores" to "anon";

grant delete on table "public"."match_scores" to "authenticated";

grant insert on table "public"."match_scores" to "authenticated";

grant references on table "public"."match_scores" to "authenticated";

grant select on table "public"."match_scores" to "authenticated";

grant trigger on table "public"."match_scores" to "authenticated";

grant truncate on table "public"."match_scores" to "authenticated";

grant update on table "public"."match_scores" to "authenticated";

grant delete on table "public"."match_scores" to "service_role";

grant insert on table "public"."match_scores" to "service_role";

grant references on table "public"."match_scores" to "service_role";

grant select on table "public"."match_scores" to "service_role";

grant trigger on table "public"."match_scores" to "service_role";

grant truncate on table "public"."match_scores" to "service_role";

grant update on table "public"."match_scores" to "service_role";

grant delete on table "public"."matchs" to "anon";

grant insert on table "public"."matchs" to "anon";

grant references on table "public"."matchs" to "anon";

grant select on table "public"."matchs" to "anon";

grant trigger on table "public"."matchs" to "anon";

grant truncate on table "public"."matchs" to "anon";

grant update on table "public"."matchs" to "anon";

grant delete on table "public"."matchs" to "authenticated";

grant insert on table "public"."matchs" to "authenticated";

grant references on table "public"."matchs" to "authenticated";

grant select on table "public"."matchs" to "authenticated";

grant trigger on table "public"."matchs" to "authenticated";

grant truncate on table "public"."matchs" to "authenticated";

grant update on table "public"."matchs" to "authenticated";

grant delete on table "public"."matchs" to "service_role";

grant insert on table "public"."matchs" to "service_role";

grant references on table "public"."matchs" to "service_role";

grant select on table "public"."matchs" to "service_role";

grant trigger on table "public"."matchs" to "service_role";

grant truncate on table "public"."matchs" to "service_role";

grant update on table "public"."matchs" to "service_role";

grant delete on table "public"."players" to "anon";

grant insert on table "public"."players" to "anon";

grant references on table "public"."players" to "anon";

grant select on table "public"."players" to "anon";

grant trigger on table "public"."players" to "anon";

grant truncate on table "public"."players" to "anon";

grant update on table "public"."players" to "anon";

grant delete on table "public"."players" to "authenticated";

grant insert on table "public"."players" to "authenticated";

grant references on table "public"."players" to "authenticated";

grant select on table "public"."players" to "authenticated";

grant trigger on table "public"."players" to "authenticated";

grant truncate on table "public"."players" to "authenticated";

grant update on table "public"."players" to "authenticated";

grant delete on table "public"."players" to "service_role";

grant insert on table "public"."players" to "service_role";

grant references on table "public"."players" to "service_role";

grant select on table "public"."players" to "service_role";

grant trigger on table "public"."players" to "service_role";

grant truncate on table "public"."players" to "service_role";

grant update on table "public"."players" to "service_role";

grant delete on table "public"."teams" to "anon";

grant insert on table "public"."teams" to "anon";

grant references on table "public"."teams" to "anon";

grant select on table "public"."teams" to "anon";

grant trigger on table "public"."teams" to "anon";

grant truncate on table "public"."teams" to "anon";

grant update on table "public"."teams" to "anon";

grant delete on table "public"."teams" to "authenticated";

grant insert on table "public"."teams" to "authenticated";

grant references on table "public"."teams" to "authenticated";

grant select on table "public"."teams" to "authenticated";

grant trigger on table "public"."teams" to "authenticated";

grant truncate on table "public"."teams" to "authenticated";

grant update on table "public"."teams" to "authenticated";

grant delete on table "public"."teams" to "service_role";

grant insert on table "public"."teams" to "service_role";

grant references on table "public"."teams" to "service_role";

grant select on table "public"."teams" to "service_role";

grant trigger on table "public"."teams" to "service_role";

grant truncate on table "public"."teams" to "service_role";

grant update on table "public"."teams" to "service_role";

grant delete on table "public"."tournament_teams" to "anon";

grant insert on table "public"."tournament_teams" to "anon";

grant references on table "public"."tournament_teams" to "anon";

grant select on table "public"."tournament_teams" to "anon";

grant trigger on table "public"."tournament_teams" to "anon";

grant truncate on table "public"."tournament_teams" to "anon";

grant update on table "public"."tournament_teams" to "anon";

grant delete on table "public"."tournament_teams" to "authenticated";

grant insert on table "public"."tournament_teams" to "authenticated";

grant references on table "public"."tournament_teams" to "authenticated";

grant select on table "public"."tournament_teams" to "authenticated";

grant trigger on table "public"."tournament_teams" to "authenticated";

grant truncate on table "public"."tournament_teams" to "authenticated";

grant update on table "public"."tournament_teams" to "authenticated";

grant delete on table "public"."tournament_teams" to "service_role";

grant insert on table "public"."tournament_teams" to "service_role";

grant references on table "public"."tournament_teams" to "service_role";

grant select on table "public"."tournament_teams" to "service_role";

grant trigger on table "public"."tournament_teams" to "service_role";

grant truncate on table "public"."tournament_teams" to "service_role";

grant update on table "public"."tournament_teams" to "service_role";

grant delete on table "public"."tournaments" to "anon";

grant insert on table "public"."tournaments" to "anon";

grant references on table "public"."tournaments" to "anon";

grant select on table "public"."tournaments" to "anon";

grant trigger on table "public"."tournaments" to "anon";

grant truncate on table "public"."tournaments" to "anon";

grant update on table "public"."tournaments" to "anon";

grant delete on table "public"."tournaments" to "authenticated";

grant insert on table "public"."tournaments" to "authenticated";

grant references on table "public"."tournaments" to "authenticated";

grant select on table "public"."tournaments" to "authenticated";

grant trigger on table "public"."tournaments" to "authenticated";

grant truncate on table "public"."tournaments" to "authenticated";

grant update on table "public"."tournaments" to "authenticated";

grant delete on table "public"."tournaments" to "service_role";

grant insert on table "public"."tournaments" to "service_role";

grant references on table "public"."tournaments" to "service_role";

grant select on table "public"."tournaments" to "service_role";

grant trigger on table "public"."tournaments" to "service_role";

grant truncate on table "public"."tournaments" to "service_role";

grant update on table "public"."tournaments" to "service_role";

create policy "Allow read to all"
on "public"."match_scores"
as permissive
for select
to anon, authenticated
using (true);


create policy "Allow read to all"
on "public"."matchs"
as permissive
for select
to anon, authenticated
using (true);


create policy "allow read to all"
on "public"."players"
as permissive
for select
to anon, authenticated
using (true);


create policy "allow read to all"
on "public"."teams"
as permissive
for select
to anon, authenticated
using (true);


create policy "Allow read to all"
on "public"."tournament_teams"
as permissive
for select
to anon, authenticated
using (true);


create policy "Allow read to all"
on "public"."tournaments"
as permissive
for select
to anon, authenticated
using (true);



